### ISSUE TITLE
blob already deleted issue - conda-hosted repository

### ISSUE THREAD

**Issue by jaroslawk** [sonatype-nexus-community/nexus-repository-conda#22]
* **What are you trying to do?**
Doing the development of conda-hosted repository #21  I have stumbled uppon the following exception:

nexus_1  | 2019-09-16 15:50:35,791+0000 INFO  [qtp2082335914-67] *UNKNOWN org.sonatype.nexus.repository.upload.internal.UploadManagerImpl - Uploading component with parameters: repository="conda-hosted" format="conda"
nexus_1  | 2019-09-16 15:50:35,791+0000 INFO  [qtp2082335914-67] *UNKNOWN org.sonatype.nexus.repository.upload.internal.UploadManagerImpl - Asset with parameters: file="ablog-0.9.2-py_0.tar.bz2" path="noarch/ablog-0.9.2-py_0.tar.bz2"
nexus_1  | 2019-09-16 15:50:35,794+0000 DEBUG [qtp2082335914-67] *UNKNOWN org.sonatype.nexus.plugins.conda.internal.hosted.CondaHostedFacetImpl - Find component with name ablog and path: noarch/ablog-0.9.2-py_0.tar.bz2
nexus_1  | 2019-09-16 15:50:35,796+0000 DEBUG [qtp2082335914-67] *UNKNOWN org.sonatype.nexus.plugins.conda.internal.hosted.CondaHostedFacetImpl - Create new component and asset
nexus_1  | 2019-09-16 15:50:35,839+0000 DEBUG [qtp2082335914-67] *UNKNOWN org.sonatype.nexus.plugins.conda.internal.hosted.CondaHostedFacetImpl - Find component with name ablog and path: noarch/ablog-0.9.2-py_0.tar.bz2
nexus_1  | 2019-09-16 15:50:35,840+0000 DEBUG [qtp2082335914-67] *UNKNOWN org.sonatype.nexus.plugins.conda.internal.hosted.CondaHostedFacetImpl - Create new component and asset
nexus_1  | 2019-09-16 15:50:35,841+0000 WARN  [qtp2082335914-67] *UNKNOWN org.sonatype.nexus.blobstore.file.FileBlobStore - Can't open input stream to blob tmp$5867f1b7-5412-4a1c-ada8-b2e16fdd25aa as file /nexus-data/blobs/default/content/tmp/tmp$5867f1b7-5412-4a1c-ada8-b2e16fdd25aa.bytes not found
nexus_1  | 2019-09-16 15:50:35,848+0000 WARN  [qtp2082335914-67] *UNKNOWN org.sonatype.nexus.siesta.internal.UnexpectedExceptionMapper - (ID e210998a-3da8-4034-a37d-83c421b75a38) Unexpected exception: org.sonatype.nexus.blobstore.api.BlobStoreException: BlobId: tmp$5867f1b7-5412-4a1c-ada8-b2e16fdd25aa, Blob has been deleted
nexus_1  | org.sonatype.nexus.blobstore.api.BlobStoreException: BlobId: tmp$5867f1b7-5412-4a1c-ada8-b2e16fdd25aa, Blob has been deleted
nexus_1  | 	at org.sonatype.nexus.blobstore.file.FileBlobStore.checkExists(FileBlobStore.java:629)
nexus_1  | 	at org.sonatype.nexus.blobstore.file.FileBlobStore.access$1(FileBlobStore.java:624)
nexus_1  | 	at org.sonatype.nexus.blobstore.file.FileBlobStore$FileBlob.getInputStream(FileBlobStore.java:862)
nexus_1  | 	at org.sonatype.nexus.repository.storage.TempBlob.get(TempBlob.java:102)
nexus_1  | 	at org.sonatype.nexus.repository.storage.TempBlob.get(TempBlob.java:1)
nexus_1  | 	at org.sonatype.nexus.repository.storage.DefaultContentValidator.determineContentType(DefaultContentValidator.java:71)
nexus_1  | 	at org.sonatype.nexus.repository.storage.StorageTxImpl.determineContentType(StorageTxImpl.java:943)
nexus_1  | 	at org.sonatype.nexus.repository.storage.StorageTxImpl.buildStorageHeaders(StorageTxImpl.java:688)
nexus_1  | 	at org.sonatype.nexus.repository.storage.StorageTxImpl.createBlob(StorageTxImpl.java:660)
nexus_1  | 	at org.sonatype.nexus.repository.storage.StorageTxImpl.setBlob(StorageTxImpl.java:912)
nexus_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nexus_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nexus_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nexus_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
nexus_1  | 	at org.sonatype.nexus.common.stateguard.SimpleMethodInvocation.proceed(SimpleMethodInvocation.java:53)
nexus_1  | 	at org.sonatype.nexus.common.stateguard.StateGuardAspect$1.invoke(StateGuardAspect.java:69)
nexus_1  | 	at com.sun.proxy.$Proxy200.setBlob(Unknown Source)
nexus_1  | 	at org.sonatype.nexus.plugins.conda.internal.hosted.CondaHostedFacetImpl.doPutContent(CondaHostedFacetImpl.java:125)
nexus_1  | 	at org.sonatype.nexus.plugins.conda.internal.hosted.CondaHostedFacetImpl.upload(CondaHostedFacetImpl.java:91)

* **What feature or behavior is this required for?**
Who can help with this kind of issues? 
What is the proper way to get help?

cc @DarthHater @bhamail

**Comment by jaroslawk** [comment]
found the solution
